openapi: 3.0.0
info:
  title: Flight List and Numbers
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /flightLists:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                checked-in-passenger:
                  value:
                    flightName: AIR_INDIA
                    codeNumber: F2GLK5

                   
              schema:
                $ref: /reference/models/flightListConfig.yaml
